### ISSUE TITLE
Image comparison algorithms

### ISSUE THREAD

**Issue by dngoodman** [CSC545-TEAM-RED/PROJECT-X#2] opened 2015-04-14 18:36 UTC
Histogram matching - get sums of colors from both images and compare them

**Comment by dngoodman** [comment] 2015-04-14 18:37
Palette match - generate a palette from both images and compare the resultant palettes

**Comment by dngoodman** [comment] 2015-04-14 18:37
Direct pixel match - compare the pixels in both images

**Comment by dngoodman** [comment] 2015-04-14 18:38
Keypoint matching - find areas of high importance in an image

**Comment by shaneallgeier** [comment] 2015-05-12 18:00
Duplicate of #3

**Closed as completed by shaneallgeier** 2015-05-12 18:00 UTC
